	unitDef = {
	  unitname            = [[baircarrier]],
	  name                = [[Maeda Class Cruiser]],
	  description         = [[Air Carrier]],
	  acceleration        = 0.158,
          amphibious          = false,
          bankscale           = [[1]],
	  bmcode              = [[1]],
	  brakeRate           = 6.25,
	  buildCostEnergy     = 5000,
	  buildCostMetal      = 5000,
	  builder             = false,
	  buildPic            = [[baircarrier.png]],
	  buildTime           = 5000,
	  canAttack           = true,
          canFly              = true,
	  canGuard            = true,
	  canload             = [[1]],
	  canMove             = true,
	  canPatrol           = true,
	  canstop             = [[1]],
          canSubmerge         = false,
	  category            = [[GUNSHIP]],

          collisionVolumeOffsets = [[0 30 0]],
          collisionVolumeScales  = [[150 170 370]],
          collisionVolumeTest    = 1,
          collisionVolumeType    = [[box]],

          collide             = false,
	  corpse              = [[DEAD]],
          cruiseAlt           = 250,
          reclaimable                   = false,
	
	  defaultmissiontype  = [[VTOL_standby]],
	  explodeAs           = [[GUNSHIPEX]],
          floater             = true,
          footprintx          = 5,
	  footprintZ          = 5,
	  iconType            = [[airtransport]],
	  idleAutoHeal        = 5,
	  idleTime            = 1800,
	  maneuverleashlength = [[1280]],
	  mass                = 2500,
	  maxDamage           = 5000,
	  maxVelocity         = 8,
	  minCloakDistance    = 75,
	  noAutoFire          = false,
	  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE GUNSHIP SUB]],
	  objectName          = [[baircarrier.s3o]],
	  releaseHeld         = true,
          scale               = [[1]],
	  seismicSignature    = 0,
	  selfDestructAs      = [[GUNSHIPEX]],
	  side                = [[NKG]],
	  sightDistance       = 572,
	  smoothAnim          = true,
	  steeringmode        = [[1]],
	  TEDClass            = [[VTOL]],
	  transportCapacity   = 1,
	  transportSize       = 25,
	  turnInPlace         = 0,
	  turnRate            = 420,
	  verticalSpeed       = 30,
	  workerTime          = 0,
          script              = [[baircarrier.lua]],

	
	  weapons             = {
	
	    {
	      def                = [[ARMFIG_MISSILE]],
	      badTargetCategory  = [[GUNSHIP]],
	      onlyTargetCategory = [[FIXEDWING GUNSHIP]],
	    },

	    {
	      def                = [[ARMFIG_MISSILE]],
	      badTargetCategory  = [[GUNSHIP]],
	      onlyTargetCategory = [[FIXEDWING GUNSHIP]],
	    },
	
	  },
	
	
	  weaponDefs          = {
	
	    ARMFIG_MISSILE         = {
	      name                    = [[Guided AA Missiles]],
	      areaOfEffect            = 48,
	      avoidFriendly           = true,
	      canattackground         = false,
	      collideFriendly         = false,
	      craterBoost             = 1,
	      craterMult              = 2,
	      cylinderTargetting      = 1,
	
	      damage                  = {
	        default = 20,
	        planes  = [[200]],
	        subs    = 10,
	      },
	
	      explosionGenerator      = [[custom:WEAPEXP_PUFF]],
	      fireStarter             = 70,
	      flightTime              = 3,
	      guidance                = true,
	      impulseBoost            = 0,
	      impulseFactor           = 0.4,
	      interceptedByShieldType = 2,
	      lineOfSight             = true,
	      metalpershot            = 0,
	      model                   = [[baamissile.s3o]],
	      noSelfDamage            = true,
	      range                   = 530,
	      reloadtime              = 4.5,
	      renderType              = 1,
	      selfprop                = true,
	      smokedelay              = [[0.1]],
	      smokeTrail              = true,
	      soundHit                = [[OTAunit/XPLOSML2]],
	      soundStart              = [[OTAunit/ROCKLIT3]],
	      startsmoke              = [[1]],
	      startVelocity           = 200,
	      tolerance               = 22000,
	      tracks                  = true,
	      turnRate                = 30000,
	      weaponAcceleration      = 550,
	      weaponTimer             = 5,
	      weaponType              = [[MissileLauncher]],
	      weaponVelocity          = 750,
	    },
	
	  },
	
	
	  featureDefs         = {
	
	    DEAD  = {
	      description      = [[Wreckage - Jeffy]],
	      blocking         = false,
	      category         = [[corpses]],
	      damage           = 160,
	      energy           = 0,
	      featureDead      = [[DEAD2]],
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 2,
	      footprintZ       = 2,
	      height           = [[4]],
	      hitdensity       = [[100]],
	      metal            = 15,
	      object           = [[bgenericwreckage.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 15,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },
	
	
	    DEAD2 = {
	      description      = [[Debris - Jeffy]],
	      blocking         = false,
	      category         = [[heaps]],
	      damage           = 160,
	      energy           = 0,
	      featureDead      = [[HEAP]],
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 2,
	      footprintZ       = 2,
	      height           = [[4]],
	      hitdensity       = [[100]],
	      metal            = 15,
	      object           = [[2X2F]],
	      reclaimable      = true,
	      reclaimTime      = 15,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },
	
	  },
	
	}
	
	return lowerkeys({ baircarrier = unitDef })
