local kamphreztank = {
	name                = [[Resurrection Team]],
	description         = [[Resurrection Tank - Mobile resurrection unit.  Has weak stun beam.]],
        acceleration        = 0.04,
        brakerate           = 0.02,
        buildpic            = [[kamphreztank.png]],
	buildCostEnergy     = 150,
	buildCostMetal      = 150,
        buildDistance       = 180,
        builder             = true,

	buildoptions		= {
	},

	buildTime           = 15,
	canAttack           = true,
        canAssist           = true,
        canGuard            = true,
	canMove		    = true,
	canPatrol           = true,
        canReclaim          = true,
	canResurrect        = true,
	canstop             = [[1]],
	category            = [[HOVER]],
        corpse              = [[DEAD]],
        reclaimable         = false,


	defaultmissiontype  = [[Standby]],
        energyMake          = 0,
	explodeAs           = [[BIG_UNITEX]],
        footprintx          = 2,
	footprintZ          = 2,
	idleAutoHeal        = 0,
	maneuverleashlength = [[640]],
	mass                = 50,
	maxDamage           = 1000,
        maxSlope            = 27,
	maxVelocity         = 1.75,
        minWaterDepth       = 0,
        metalMake           = 0,
	minCloakDistance    = 75,
	movementClass       = [[TANK3]],
        noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK]],
	objectName          = "kamphreztank.s3o",
        onoffable           = false,
        seismicSignature    = 4,
        selfDestructAs      = [[BIG_UNITEX]],
        side                = [[PN]],
        sightDistance       = 512,
	smoothAnim          = true,
	steeringmode        = [[1]],
	TEDClass            = [[TANK]],
        terraformSpeed      = 300,
	turninplace         = 0,
	turnInPlace         = 0,
	turnRate            = 560,
	showNanospray	    = 0,
	workerTime          = 1,
	script		    = "kamphreztank.lua",

	  featureDefs         = {
	
	    DEAD  = {
	      description      = [[Wreckage - Resurrection Tank]],
	      blocking         = true,
	      category         = [[corpses]],
	      damage           = 2200,
	      energy           = 0,
	      featureDead      = [[DEAD2]],
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 3,
	      footprintZ       = 3,
	      height           = [[20]],
	      hitdensity       = [[100]],
	      metal            = 70,
	      object           = [[bgenericwreckage.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 70,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },
	
	
	    DEAD2 = {
	      description      = [[Debris - Resurrection Tank]],
	      blocking         = false,
	      category         = [[heaps]],
	      damage           = 2200,
	      energy           = 0,
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 2,
	      footprintZ       = 2,
	      height           = [[4]],
	      hitdensity       = [[100]],
	      metal            = 70,
	      object           = [[b2x2heap.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 70,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },

  	  },

	}


return lowerkeys({ ["kamphreztank"] = kamphreztank })