local kcommander = {
	name                = [[Commander]],
	description         = [[He gets stuff done!!]],
        acceleration        = 0.18,
	activateWhenBuilt   = true,
	amphibious          = [[1]],
	autoHeal            = 5,
	bmcode              = [[1]],
        brakerate           = 0.375,
	buildCostEnergy     = 1800,
	buildCostMetal      = 1800,
        buildDistance       = 240,
        builder             = true,

	buildoptions		= {
                [[kufact1]],
		[[kmex]],
		[[kfieldcannon]],
		[[kfieldbattery]],
		[[kadvestore]],
		[[kfieldmetalmaker]],
		[[kfieldmetalstorage]],
		[[kfloatingfieldbattery]],
		[[kfieldgun]],
		[[ksolarcollector]],
		[[kwall]],
		[[ktidalcollector]],
		[[ktorpedolauncher]],
		[[kfloatingfieldmetalmaker]],
		[[kseawall]],
		[[kspreadrocketaa]],
		[[knsfieldlaser]],
		[[klightmine]],
		[[kfieldlaser]],
		[[knslightmine]],
		[[knsfieldradar]],
		[[kconstructionvehicle]],
		[[kmechfactory]],
		[[kfieldradar]],
		[[knsspreadrocketaa]],
		[[kamphibiousartillery]],
		[[kamphreztank]],
		[[terraunit]],

	},

        buildpic            = [[kcommander.png]],
	buildTime           = 1800,
        canAssist           = true,
	canDGun             = true,
        canGuard            = true,
	canMove		    = true,
	canPatrol           = true,
        canReclaim          = true,
	canstop             = [[1]],
	category            = [[LAND FIREPROOF]],
	cloackCost          = 10,
	cloakCostMoving     = 50,
	commander           = true,
        corpse              = [[DEAD]],
        reclaimable         = false,

	defaultmissiontype  = [[Standby]],
        energyMake          = 7.2,
	energyStorage       = 1000,
	energyUse           = 0,
	explodeAs           = [[ESTOR_BUILDINGEX]],
        footprintx          = 5,
	footprintZ          = 5,
	hideDamage          = true,
        iconType            = [[armcommander]],
	idleAutoHeal        = 5,
	idleTime            = 1800,
	immunetoparalyzer   = [[1]],
	maneuverleashlength = [[640]],
	mass                = 2500,
	maxDamage           = 2500,
        maxSlope            = 36,
	maxVelocity         = 1.45,
        maxWaterDepth       = 5000,
        metalMake           = 3,
	metalStorage        = 1000,
	minCloakDistance    = 100,
	movementClass       = [[AKBOT2]],
	moveState           = 0,
        noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK]],
	norestrict          = [[1]],
	objectName          = "kcommander.s3o",
        seismicSignature    = 16,
        selfDestructAs      = [[ESTOR_BUILDINGEX]],

	  sfxtypes            = {
	
	    explosiongenerators = {
	      [[custom:COMGATE]],
	    },
	
	  },

	showPlayerName      = true,
        side                = [[PN]],
        sightDistance       = 500,
	smoothAnim          = true,
	sonarDistance       = 300,
	steeringmode        = [[2]],
	TEDClass            = [[COMMANDER]],
        terraformSpeed      = 600,
	reclaimSpeed        = 300,
	turnRate            = 1148,
	showNanospray	    = 0,
	upright             = true,
	workerTime          = 12,
	script		    = "kcommander.lua",

	  weapons             = {

	    {
	      def = [[DISINTEGRATOR]],
	    },
	
	
	    {
	      def                = [[LASER]],
	      badTargetCategory  = [[FIXEDWING]],
	      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
	    },

	    {
	      def                = [[LASER]],
	      badTargetCategory  = [[FIXEDWING]],
	      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
	    },

	    {
	      def                = [[LASER]],
	      badTargetCategory  = [[FIXEDWING]],
	      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
	    },

	    {
	      def                = [[LASER]],
	      badTargetCategory  = [[FIXEDWING]],
	      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
	    },
	
	  },

	  weaponDefs          = {
	
	    DISINTEGRATOR = {
	      name                    = [[Disintegrator]],
	      areaOfEffect            = 36,
	      avoidFeature            = false,
	      avoidFriendly           = false,
	      avoidNeutral            = false,
	      commandfire             = true,
	      craterBoost             = 1,
	      craterMult              = 6,
	
	      damage                  = {
	        default    = 99999,
	        commanders = [[1]],
	      },
	
	      energypershot           = 300,
	      explosionGenerator      = [[custom:DGUNTRACE]],
	      impulseBoost            = 0,
	      impulseFactor           = 0,
	      interceptedByShieldType = 1,
	      noExplode               = true,
	      noSelfDamage            = true,
	      range                   = 250,
	      reloadtime              = 1,
	      renderType              = 3,
	      soundHit                = [[OTAunit/XPLOMAS2]],
	      soundStart              = [[OTAunit/DISIGUN1]],
	      soundTrigger            = true,
	      tolerance               = 10000,
	      turret                  = true,
	      weaponTimer             = 4.2,
	      weaponType              = [[DGun]],
	      weaponVelocity          = 300,
	    },

	    LASER = {
	      name                    = [[Laser Blaster]],
	      areaOfEffect            = 8,
	      beamWeapon              = true,
	      cegTag                  = [[redlaser_ak]],
	      coreThickness           = 0.5,
	      craterBoost             = 1,
	      craterMult              = 2,
	
	      damage                  = {
	        default = 16.59,
	        planes  = 16.59,
	        subs    = 0.829,
	      },
	
	      duration                = 0.02,
	      energypershot           = 0,
	      explosionGenerator      = [[custom:GATORLASERFLASH]],
	      fireStarter             = 50,
	      heightMod               = 1,
	      impactOnly              = true,
	      impulseBoost            = 0,
	      impulseFactor           = 0.4,
	      interceptedByShieldType = 1,
	      lineOfSight             = true,
	      noSelfDamage            = true,
	      range                   = 2300,
	      reloadtime              = 0.19,
	      renderType              = 0,
	      rgbColor                = [[1 0 0]],
	      soundStart              = [[OTAunit/lasrlit3]],
	      soundTrigger            = true,
	      targetMoveError         = 0.15,
	      thickness               = 3.76646385884692,
	      tolerance               = 10000,
	      turret                  = true,
	      weaponType              = [[LaserCannon]],
	      weaponVelocity          = 1500,
	    },
	
	  },

	  featureDefs         = {
	
	    DEAD  = {
	      description      = [[Wreckage - Pioneer]],
	      blocking         = true,
	      category         = [[corpses]],
	      damage           = 2200,
	      energy           = 0,
	      featureDead      = [[DEAD2]],
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 3,
	      footprintZ       = 3,
	      height           = [[20]],
	      hitdensity       = [[100]],
	      metal            = 70,
	      object           = [[pioneer_dead]],
	      reclaimable      = true,
	      reclaimTime      = 70,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },
	
	
	    DEAD2 = {
	      description      = [[Debris - Pioneer]],
	      blocking         = false,
	      category         = [[heaps]],
	      damage           = 2200,
	      energy           = 0,
	      featureDead      = [[HEAP]],
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 3,
	      footprintZ       = 3,
	      height           = [[4]],
	      hitdensity       = [[100]],
	      metal            = 70,
	      object           = [[debris3x3c.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 70,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },
	
	
	    HEAP  = {
	      description      = [[Debris - Pioneer]],
	      blocking         = false,
	      category         = [[heaps]],
	      damage           = 2200,
	      energy           = 0,
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 3,
	      footprintZ       = 3,
	      height           = [[4]],
	      hitdensity       = [[100]],
	      metal            = 35,
	      object           = [[debris3x3c.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 35,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },

  	  },

	}


return lowerkeys({ ["kcommander"] = kcommander })