local kseacon = {
	name                = [[Sea Constructor]],
	description         = [[Sea Constructor]],
        acceleration        = 0.05,
	bmcode              = [[1]],
        brakerate           = 0.5,
	buildCostEnergy     = 140,
	buildCostMetal      = 140,
        buildDistance       = 300,
        builder             = true,

	buildoptions		= {
                [[bseamex]],
		[[bseapowerplant]],
		[[bseametalstorage]],
		[[bseaenergystorage]],
		[[bshipyard]],
		[[bsubpens]],
		[[bsearadartower]],
		[[btorpedoturret]],
	},

        buildpic            = [[kseacon.png]],
	buildTime           = 10,
        canAssist           = false,
        canGuard            = true,
	canMove		    = true,
	canPatrol           = true,
        canReclaim          = true,
	canstop             = [[1]],
	category            = [[SHIP]],
        corpse              = [[DEAD]],
        reclaimable         = false,


	defaultmissiontype  = [[Standby]],
        energyMake          = 0.15,
	energyUse           = 0,
	explodeAs           = [[SMALL_UNITEX]],
	floater             = true,
        footprintx          = 3,
	footprintZ          = 3,
	idleAutoHeal        = 0,
	maneuverleashlength = [[640]],
	mass                = 90,
	maxDamage           = 350,
	maxVelocity         = 2,
        metalMake           = 0.15,
	minCloakDistance    = 75,
        minWaterDepth       = 5,
	movementClass       = [[BOAT3]],
	noAutoFire          = false,
        noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK]],
	objectName          = "kseacon.s3o",
        seismicSignature    = 4,
        selfDestructAs      = [[SMALL_UNITEX]],
	showNanoSpray       = false,
        side                = [[NKG]],
        sightDistance       = 500,
	smoothAnim          = true,
	steeringmode        = [[1]],
	TEDClass            = [[SHIP]],
        terraformSpeed      = 600,
	reclaimSpeed        = 300,
	turnRate            = 448,
	workerTime          = 1,
	waterline           = 2,
	script		    = "kseacon.lua",

	  featureDefs         = {
	
	    DEAD  = {
	      description      = [[Wreckage - Naval Engineer]],
	      blocking         = true,
	      category         = [[corpses]],
	      damage           = 2200,
	      energy           = 0,
	      featureDead      = [[DEAD2]],
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 3,
	      footprintZ       = 3,
	      height           = [[20]],
	      hitdensity       = [[100]],
	      metal            = 70,
	      object           = [[bgenericwreckage.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 70,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },
	
	
	    DEAD2 = {
	      description      = [[Debris - Naval Engineer]],
	      blocking         = false,
	      category         = [[heaps]],
	      damage           = 2200,
	      energy           = 0,
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 3,
	      footprintZ       = 3,
	      height           = [[4]],
	      hitdensity       = [[100]],
	      metal            = 70,
	      object           = [[b3x3heap.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 70,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },

  	  },

	}


return lowerkeys({ ["kseacon"] = kseacon })