	unitDef = {
	  unitname            = [[kstealthtank]],
	  name                = [[Stealthy Tank!]],
	  description         = [[It's a spy in a tank!]],
	  acceleration        = 0.04,
	  bmcode              = [[1]],
	  brakeRate           = 0.055,
	  buildCostEnergy     = 250,
	  buildCostMetal      = 250,
	  builder             = false,
	  buildPic            = [[kstealthtank.png]],
	  buildTime           = 250,
	  canAttack           = true,
	  canGuard            = true,
	  canMove             = true,
	  canPatrol           = true,
	  canstop             = [[1]],
	  category            = [[LAND]],
	  cloakCost           = 0.2,
	  cloakCostMoving     = 1,
	  corpse              = [[DEAD]],
          reclaimable         = false,
	
	  defaultmissiontype  = [[Standby]],
	  explodeAs           = [[BIG_UNITEX]],
	  footprintX          = 3,
	  footprintZ          = 3,
	  iconType            = [[tankscout]],
	  idleAutoHeal        = 5,
	  idleTime            = 1800,
	  initCloaked         = false,
	  leaveTracks         = true,
	  maneuverleashlength = [[640]],
	  mass                = 125,
	  maxDamage           = 600,
	  maxSlope            = 18,
	  maxVelocity         = 3.2,
	  maxWaterDepth       = 22,
	  movementClass       = [[TANK3]],
	  noAutoFire          = false,
	  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE SUB]],
	  objectName          = [[kstealthtank.s3o]],
	  seismicSignature    = 16,
	  selfDestructAs      = [[BIG_UNITEX]],
	  side                = [[PN]],
	  sightDistance       = 440,
	  smoothAnim          = true,
	  stealth             = true,
	  steeringmode        = [[1]],
	  TEDClass            = [[TANK]],
	  trackOffset         = 0,
	  trackStrength       = 6,
	  trackStretch        = 1,
	  trackType           = [[StdTank]],
	  trackWidth          = 29,
	  turninplace         = 0,
	  turnRate            = 710.8,
	  workerTime          = 0,
          script              = [[kstealthtank.lua]],
	
	  weapons             = {
	
	    {
	      def                = [[LASER]],
	      badTargetCategory  = [[FIXEDWING]],
	      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
	    },

	    {
	      def                = [[LASER]],
	      badTargetCategory  = [[FIXEDWING]],
	      onlyTargetCategory = [[FIXEDWING LAND SINK SHIP SWIM FLOAT GUNSHIP HOVER]],
	    },
	
	  },
	
	
	  weaponDefs          = {
	
	    LASER = {
	      name                    = [[Laser Blaster]],
	      areaOfEffect            = 8,
	      beamWeapon              = true,
	      cegTag                  = [[redlaser_ak]],
	      coreThickness           = 0.5,
	      craterBoost             = 1,
	      craterMult              = 2,
	
	      damage                  = {
	        default = 16.59,
	        planes  = 16.59,
	        subs    = 0.829,
	      },
	
	      duration                = 0.02,
	      energypershot           = 0,
	      explosionGenerator      = [[custom:GATORLASERFLASH]],
	      fireStarter             = 50,
	      heightMod               = 1,
	      impactOnly              = true,
	      impulseBoost            = 0,
	      impulseFactor           = 0.4,
	      interceptedByShieldType = 1,
	      lineOfSight             = true,
	      noSelfDamage            = true,
	      range                   = 2300,
	      reloadtime              = 0.19,
	      renderType              = 0,
	      rgbColor                = [[1 0 0]],
	      soundStart              = [[OTAunit/lasrlit3]],
	      soundTrigger            = true,
	      targetMoveError         = 0.15,
	      thickness               = 3.76646385884692,
	      tolerance               = 10000,
	      turret                  = true,
	      weaponType              = [[LaserCannon]],
	      weaponVelocity          = 1500,
	    },
	
	  },
	
	
	  featureDefs         = {
	
	    DEAD  = {
	      description      = [[Wreckage - Jeffy]],
	      blocking         = false,
	      category         = [[corpses]],
	      damage           = 160,
	      energy           = 0,
	      featureDead      = [[DEAD2]],
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 2,
	      footprintZ       = 2,
	      height           = [[4]],
	      hitdensity       = [[100]],
	      metal            = 15,
	      object           = [[bgenericwreckage.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 15,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },
	
	
	    DEAD2 = {
	      description      = [[Debris - Jeffy]],
	      blocking         = false,
	      category         = [[heaps]],
	      damage           = 160,
	      energy           = 0,
	      featureDead      = [[HEAP]],
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 2,
	      footprintZ       = 2,
	      height           = [[4]],
	      hitdensity       = [[100]],
	      metal            = 15,
	      object           = [[2X2F]],
	      reclaimable      = true,
	      reclaimTime      = 15,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },
	
	  },
	
	}
	
	return lowerkeys({ kstealthtank = unitDef })