	unitDef = {
	  unitname            = [[kwall]],
	  name                = [[Terrestrial Turret]],
	  description         = [[Anti-Land Turret - Cheap, mildly effective turret designed to counter terrestrial units.  Fires two cannons.]],
	  acceleration        = 0,
	  bmcode              = [[0]],
	  brakeRate           = 0,
	  buildCostEnergy     = 350,
	  buildCostMetal      = 350,
	  builder             = false,
	  buildPic            = [[kwall.png]],
	  buildTime           = 20,
	  canAttack           = true,
	  canstop             = [[1]],
	  category            = [[SINK]],
	  corpse              = [[WALL]],
          reclaimable         = false,
	
	  explodeAs           = [[SMALL_BUILDINGEX]],
	  isFeature           = true,
          footprintx          = 4,
	  footprintZ          = 4,
	  idleAutoHeal        = 0,
	  levelGround         = false,
	  mass                = 35,
	  maxDamage           = 4500,
          maxSlope            = 36,
	  maxVelocity         = 0,
          maxWaterDepth       = 0,
	  minCloakDistance    = 150,
	  noAutoFire          = false,
	  noChaseCategory     = [[FIXEDWING LAND SHIP SATELLITE SWIM GUNSHIP SUB HOVER]],
	  objectName          = [[kwall.s3o]],
	  seismicSignature    = 4,
	  selfDestructAs      = [[SMALL_BUILDINGEX]],
	  side                = [[PN]],
	  sightDistance       = 473,
	  smoothAnim          = true,
	  TEDClass            = [[FORT]],
	  turnRate            = 0,
	  workerTime          = 0,
	  yardMap             = [[oooo oooo oooo oooo]],
          script              = [[kwall.lua]],
	
	
	  featureDefs         = {
	
	  WALL = {
	    autoreclaimable    = "0",
	    blocking           = true,
	    category           = "zekewall",
	    damage             = 1000,
	    description        = "zekewall",
	    featureDead        = "DEAD2",
	    featurereclamate   = "smudge01",
	    footprintX         = 2,
	    footprintZ         = 2,
	    height             = "30",
	    hitdensity         = "100",
	    metal              = 1,
	    object             = "kwall.s3o",
	    reclaimable        = false,
 	   seqnamereclamate   = "tree1reclamate",
 	   upright            = true,
 	   world              = "allworld",
	  },
	
	
	    DEAD2 = {
	      description      = [[Debris - Anti-Land Turret]],
	      blocking         = false,
	      category         = [[heaps]],
	      damage           = 160,
	      energy           = 0,
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 4,
	      footprintZ       = 4,
	      height           = [[4]],
	      hitdensity       = [[100]],
	      metal            = 15,
	      object           = [[b4x4heap.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 15,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },
	
	  },
	
	}
	
	return lowerkeys({ kwall = unitDef })
