local armorDefs = {

  Cruiser  =  {
    "bflagship2",
    "bbattleflagship",
    "bbattlecruiser",
    "btransportcarrier2",
    "bmetalsupplyship",
    "benergysupplyship",
  },

  Building  =  {
    "bflagshipbase",
    "bmex",
    "bpowerplant",
    "bnuclearpower",
    "bmetalconverter",
    "bseamex",
    "bseapowerplant",
    "bseametalstorage",
    "bseaenergystorage",
    "bradartower",
    "bjammertower",
    "blandturret",
    "bairturret",
    "blandnavalturret",
    "bgatlingturret",
    "bmechturret",
    "bsearadartower",
    "btorpedoturret",
    "badvmex",
    "badvpowerplant",
    "badvnuclearpower",
    "badvmetalconverter",
    "badvradartower",
    "badvjammertower",
    "badvlandturret",
    "badvairturret",
    "badvlandnavalturret",
    "badvgatlingturret",
    "badvmechturret",
    "badvsearadartower",
    "badvtorpedoturret",
    "bshieldgen",
    "bmechfactory",
    "badvmechfactory",
    "btankfactory",
    "bmetaltruckdepot",
    "benergytruckdepot",
    "badvtankfactory",
    "bairport",
    "badvairport",
    "bshipyard",
    "badvshipyard",
    "bsubpens",
    "badvsubpens",
    "bbattlebeacon",
    "bmetalsupplyshipdepot",
    "benergysupplyshipdepot",
    "bexperimentalpad",
    "blanddefship",
    "blanddefmobileship",
    "bairdefship",
    "bairdefmobileship",
    "bnavydefship",
    "bnavydefmobileship",
  },

  Mech  =  {
    "bengineer1",
    "bdefensemech",
    "bbasicmech",
    "bsnipermech",
    "bsiegemech",
    "bmissilemech",
    "bengineer2",
    "bheavymech",
    "bheavysiegemech",
    "bheavymissilemech",
    "bamphmech",
    "badvamphmech",
    "bheavyassaultmech",
  },

  Tank = {
    "bmetaltruck",
    "benergytruck",
    "bassaulttank",
    "bmissiletank",
    "bartillery",
    "bsiegeartillery",
    "bradartank",
    "breztank",
    "bheavyassaulttank",
    "bvhsa",
    "badvradartank",
    "bheavymissiletank",
    "bempcannon",
    "bempcannonturret",
    "baatruck",
    "baatruckturret",
  },

  Aircraft = {
    "bflyingmech",
    "bheavyflyingmech",
    "bfighter",
    "bbomber",
    "brocketplane",
    "bradarplane",
    "badvfighter",
    "badvbomber",
    "badvrocketplane",
    "badvradarplane",
    "blaserplane",
  },

  Ship = {
    "bseaengineer1",
    "bmetalsupplyboat",
    "benergysupplyboat",
    "bbattleship",
    "brocketbattleship",
    "bartilleryship",
    "baaship",
    "bradarship",
    "bseaengineer2",
    "badvbattleship",
    "badvrocketbattleship",
    "blras",
    "badvaaship",
    "badvradarship",
  },

  Sub = {
    "bsubmarine",
    "baasub",
    "badvsubmarine",
    "badvaasub",
  },

}

for categoryName, categoryTable in pairs(armorDefs) do
  local t = {}
  for _, unitName in pairs(categoryTable) do
    t[unitName] = 1
  end
  armorDefs[categoryName] = t
end

return armorDefs