	unitDef = {
	  unitname            = [[bhovertransport]],
	  name                = [[Saito Type Hover Transport]],
	  description         = [[Hover Transport - Transport hovercraft that is unarmed and can carry a small battalion of armed forces.]],
	  acceleration        = 0.04,
	  bmcode              = [[0]],
	  brakeRate           = 0.02,
	  buildCostEnergy     = 375,
	  buildCostMetal      = 300,
	  builder             = false,
	  buildPic            = [[bhovertransport.png]],
	  buildTime           = 40,
	  canAttack           = false,
	  canGuard            = true,
	  canload             = [[1]],
	  canMove             = true,
	  canPatrol           = true,
	  canstop             = [[1]],
          canSubmerge         = false,
	  canHover            = true,
	  category            = [[HOVER]],
          reclaimable         = false,
	  corpse              = [[DEAD]],
	
	  defaultmissiontype  = [[Standby]],
	  explodeAs           = [[BIG_UNIT]],
          footprintx          = 10,
	  footprintZ          = 10,
	  idleAutoHeal        = 0,
	  maneuverleashlength = [[640]],
	  mass                = 2500,
	  maxDamage           = 4000,
	  maxSlope            = 27,
	  maxVelocity         = 2,
	  maxWaterDepth       = 22,
	  movementClass       = [[HOVER3]],
	  minCloakDistance    = 75,
	  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE GUNSHIP SUB]],
	  objectName          = [[bhovertransport.s3o]],
	  releaseHeld         = true,
          scale               = [[1]],
	  seismicSignature    = 0,
	  selfDestructAs      = [[BIG_UNIT]],
	  side                = [[NKG]],
	  sightDistance       = 750,
	  smoothAnim          = true,
	  steeringmode        = [[1]],

	  sounds			= {
	      select = {
		"ct/hoverengine",
		},
	      ok = {
		"ct/hoverengine",
		},
	  },

	  TEDClass            = [[TANK]],
	  transportCapacity   = 30,
	  transportMass       = 6050,
	  transportSize       = 1000,
	  turnInPlace         = 0,
	  turnRate            = 420,
	  workerTime          = 0,
	  transportUnloadMethod = 0,
          script              = [[bhovertransport.lua]],
	
	
	  featureDefs         = {
	
	    DEAD  = {
	      description      = [[Wreckage - Transport Carrier]],
	      blocking         = false,
	      category         = [[corpses]],
	      damage           = 3000,
	      energy           = 0,
	      featureDead      = [[DEAD2]],
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 2,
	      footprintZ       = 2,
	      height           = [[4]],
	      hitdensity       = [[100]],
	      metal            = 150,
	      object           = [[bgenericwreckage.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 15,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },
	
	
	    DEAD2 = {
	      description      = [[Debris - Transport Carrier]],
	      blocking         = false,
	      category         = [[heaps]],
	      damage           = 2000,
	      energy           = 0,
	      featurereclamate = [[SMUDGE01]],
	      footprintX       = 7,
	      footprintZ       = 7,
	      height           = [[4]],
	      hitdensity       = [[100]],
	      metal            = 75,
	      object           = [[b7x7heap.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 15,
	      seqnamereclamate = [[TREE1RECLAMATE]],
	      world            = [[All Worlds]],
	    },
	
	  },
	
	}
	
	return lowerkeys({ bhovertransport = unitDef })
