local kairdrone = {
	name                = [[Air Drone]],
	description         = [[Blows itself up to destroy large aircraft such as Cruisers. Can cloak and doesn't appear on radar.]],
    acceleration        = 0.06,
    brakerate           = 1.5,
    buildpic            = [[kairdrone.png]],
	buildCostEnergy     = 100,
	buildCostMetal      = 100,
    buildDistance       = 150,
    builder             = false,
	buildTime           = 15,
    canAssist           = true,
	CanAttack 			= 1,
	CanCapture			= 0,
    canGuard            = true,
	canMove		  	    = true,
	canPatrol           = true,
    canReclaim          = true,
	canStop             = true,
	category            = [[GUNSHIP]],
    canFly              = true,
	collide             = true,
	corpse              = [[DEAD]],
    cruiseAlt           = 400,
	
	cloakCost           = 10,
    cloakCostMoving     = 10,
    init_Cloaked        = false,
	
	reclaimable         = false,
	stealth             = true,
    energyMake          = 1,
	explodeAs           = [[DRONE_PETARD]],
    footprintx          = 2,
	footprintZ          = 2,
	hoverAttack         = true,
	idleAutoHeal        = 1,
	leaveTracks         = false,
	mass                = 80,
	maxDamage           = 500,
    maxSlope            = 99999999,
	maxVelocity         = 7,
    maxWaterDepth       = 10000,
    metalMake           = 0,
	minCloakDistance    = 75,
    noChaseCategory     = [[MINERALS LAND SINK HOVER SHIP FLOAT SUB]],
	objectName          = "kairdrone.s3o",
    onoffable           = false,
    seismicSignature    = 4,
    selfDestructAs      = [[DRONE_PETARD]],
    side                = [[Drone]],
    sightDistance       = 500,
	sounds			= {
	      select = {
		"golgotha/vehicle_done_44khz",
		},
	      ok = {
		"golgotha/vehicle_done_44khz",
		},
	  },
	  
	smoothAnim          = true,
    terraformSpeed      = 300,
	reclaimSpeed        = 300,
	turnInPlace         = 1,
	turnRate            = 800,
	showNanospray	    = 1,
	Resurrectspeed      = 100,
	workerTime          = 1,
	script              = "kairdrone.lua",

	featureDefs         = {
	
	    DEAD  = {
	      description      = [[Wreckage - Air Drone]],
	      blocking         = true,
	      category         = [[corpses]],
	      damage           = 250,
	      energy           = 0,
	      featureDead      = [[DEAD2]],
	      footprintX       = 2,
	      footprintZ       = 2,
	      metal            = 50,
	      object           = [[wrecks/kairdronewreck.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 1500,
	    },
	
	
	    DEAD2 = {
	      description      = [[Debris - Air Drone]],
	      blocking         = false,
	      category         = [[heaps]],
	      damage           = 125,
	      energy           = 0,
	      footprintX       = 2,
	      footprintZ       = 2,
	      metal            = 25,
	      object           = [[b2x2heap.s3o]],
	      reclaimable      = true,
	      reclaimTime      = 750,
	    },

  	  },

	}


return lowerkeys({ ["kairdrone"] = kairdrone })