unitDef = {
          unitname            = [[kdroneflyer]],
          name                = [[Drone Flyer]],
          description         = [[Drone Flyer - It shoots, It flys, It spreads.]],
          acceleration        = 0.5,
          activateWhenBuilt   = true,
          airStrafe           = 1,
          amphibious          = true,
          bankscale           = [[1.5]],
          bmcode              = [[1]],
          brakeRate           = 1.88,
          buildCostEnergy     = 0,
          buildCostMetal      = 100,
          buildDistance       = 120,
          builder             = true,

           buildoptions            = {
				[[kdrone]],
                [[kdronemine]],
                [[kdronefactory]],
                [[kdroneflyer]],
               
        },

          buildPic            = [[kdroneflyer.png]],
          buildTime           = 15,
          canAssist           = true,
          CanAttack                       =1,
          CanCapture                      =1,
          canGuard            = true,
          canMove             = true,
          canPatrol           = true,
		  canReclaim          = true,
		  canstop             = [[1]],
          category            = [[GUNSHIP]],
          collide             = false,
          corpse              = [[DEAD]],
          cruiseAlt           = 180,
          reclaimable                   = false,
          defaultmissiontype  = [[VTOL_standby]],
          energyMake          = 1,
          energyUse           = 0,
          explodeAs           = [[GUNSHIPEX]],
          floater             = true,
          footprintx          = 2,
          footprintZ          = 2,
          hoverAttack         = true,
          idleAutoHeal        = 1,
          maneuverleashlength = [[1280]],
          mass                = 2500,
          maxDamage           = 2500,
          maxVelocity         = 2,
          metalMake           = 1,
          minCloakDistance    = 100,
          noAutoFire          = false,
          noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK]],
          norestrict          = [[1]],
          objectName          = [[kdroneflyer.s3o]],
          seismicSignature    = 0,
          selfDestructAs      = [[GUNSHIPEX]],
          showNanospray       = 0,
          showPlayerName      = true,
          side                = [[NKG]],
          sightDistance       = 550,
          smoothAnim          = true,
          steeringmode        = [[1]],
          TEDClass            = [[VTOL]],
          terraformSpeed      = 600,
          turnRate            = 1144,
          workerTime          = 1,
          upright             = true,
          unitRestricted      = 1,
          script              = [[kdroneflyer.lua]],



        
          weapons             = {
        
            {
              def                = [[Laser]],
              badTargetCategory  = [[GUNSHIP SINK FLOAT]],
              onlyTargetCategory = [[SWIM LAND SHIP SINK FLOAT GUNSHIP HOVER]],
            },
        
          },
        
        
        weaponDefs             = {
        
            Laser = {
              name                    = [[Burst Laser]],
              areaOfEffect            = 8,
              coreThickness           = 0.5,
              collideFriendly         = false,
              craterMult              = 0.25,
        
              damage                  = {
                Cruiser = 50,
                Building = 50,
                Mech = 50,
                Tank = 50,
                Aircraft = 50,
                Ship = 50,
                Sub = 50,
              },
        
              duration                = 0.02,
              energypershot           = 0,
              interceptedByShieldType = 1,
              heightMod               = 0.5,
              lineOfSight             = true,
              range                   = 100,
              reloadtime              = 0.5,
              rgbColor                = [[0 1 0]],
              soundStart              = [[ct/pew1]],
              targetMoveError         = 0.15,
              thickness               = 1,
              tolerance               = 10000,
              turret                  = true,
              weaponType              = [[LaserCannon]],
              weaponVelocity          = 1500,
        
              model                   = [[bsmallmissile.s3o]],
              edgeEffectiveness       = 0.5,
              flightTime              = 4,
              interceptedByShieldType = 1,
              lineOfSight             = true,
              range                   = 800,
              reloadtime              = 6,
              smokeTrail              = true,
              soundHit                = [[TAWF114b]],
              soundStart              = [[nexuiz/rocket_fire]],
              tolerance               = 8000,
              trajectoryHeight        = 0.5,
              tracks                  = false,
              turret                  = true,
              weaponType              = [[MissileLauncher]],
              weaponVelocity          = 400,
              startVelocity           = 400,
              weaponAcceleration      = 70,
            },

          },
        
        
          featureDefs         = {
        
            DEAD  = {
              description      = [[Wreckage - Flagship]],
              blocking         = false,
              category         = [[corpses]],
              damage           = 160,
              energy           = 0,
              featureDead      = [[DEAD2]],
              featurereclamate = [[SMUDGE01]],
              footprintX       = 2,
              footprintZ       = 2,
              height           = [[4]],
              hitdensity       = [[100]],
              metal            = 15,
              object           = [[bgenericwreckage.s3o]],
              reclaimable      = true,
              reclaimTime      = 15,
              seqnamereclamate = [[TREE1RECLAMATE]],
              world            = [[All Worlds]],
            },
        
        
            DEAD2 = {
              description      = [[Debris - Flagship]],
              blocking         = false,
              category         = [[heaps]],
              damage           = 160,
              energy           = 0,
              featurereclamate = [[SMUDGE01]],
              footprintX       = 7,
              footprintZ       = 7,
              height           = [[4]],
              hitdensity       = [[100]],
              metal            = 15,
              object           = [[b7x7heap.s3o]],
              reclaimable      = true,
              reclaimTime      = 15,
              seqnamereclamate = [[TREE1RECLAMATE]],
              world            = [[All Worlds]],
            },
        
          },
        
        }
        
        return lowerkeys({ kdroneflyer = unitDef })