--ct_drone_energyshot
--Green pulsing CEG for Drone shots
--derived from an effect for CA's Vulcan

return {
  ["ct_drone_energyshot"] = {
	spikes = {
	  air				= true,
	  class				= [[CExploSpikeProjectile]],
	  count				= 3,
	  ground			= true,
	  underwater		= true,
	  useairlos			= true,
	  water				= true,
	  alwaysvisible		= false,
	  properties		= {
		dir				= [[-10 r20,-10 r20,-10 r20]],
		width			= 22,
		length			= 1,
		alpha			= 1,
		alphadecay		= 0.35,
		color			= [[0, 1, 0]],
	  },
	},

	exhale = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      useairlos          = true,
      water              = true,
      alwaysVisible      = 0,
	  properties = {
        alwaysVisible      = 0,
	    airdrag            = 0.8,
        colormap           = [[1.0 0.8 0.5 0.1 0.15 0.15 0.15 0.2 0.0 0.0 0.0 0.01]],
        directional        = 0,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 17,
        particlelifespread = 15,
        particlesize       = 8,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1,
        texture            = [[]],
      },
	},

	exhale2 = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      useairlos          = true,
      water              = true,
      alwaysVisible      = 0,
	  properties = {
        alwaysVisible      = 0,
	    airdrag            = 0.8,
        colormap           = [[1.0 0.7 0.4 0.1 0.1 0.1 0.1 0.2 0.0 0.0 0.0 0.01]],
        directional        = 0,
        emitrot            = 80,
        emitrotspread      = 5,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 2,
        particlelife       = 17,
        particlelifespread = 15,
        particlesize       = 8,
        particlesizespread = 1,
        particlespeed      = 1,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 0.16,
        sizemod            = 1,
        texture            = [[]],
      },
	},
  },
}