--ct_explosion_unit_tank
--Explosion CEG for tanks
--by Sanada

return {
  ["ct_explosion_unit_tank"] = {  
	
    pop1 = {
      air                = true,
      class              = [[CHeatCloudProjectile]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      useairlos          = false,
      water              = true,
      alwaysVisible      = false,
	  properties = {
        alwaysVisible      = false,
        texture            = [[flare]],
		heat               = 10,
		maxheat            = 15,
		heatFalloff        = 1.1,
		
		size               = 3,
		sizeGrowth         = 25,
		
		pos                = [[r-2 r2, 5, r-2 r2]],
		speed              = [[0, 1 0, 0]],
      },
    },
	
    sparks = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      useairlos          = true,
      water              = true,
      alwaysVisible      = false,
	  properties = {
        alwaysVisible      = false,
	    airdrag            = 0.8,
        colormap           = [[1.0 1.0 1.0 0.04   0.9 0.5 0.2 0.01  0.8 0.1 0.1 0.01]],
        directional        = 0,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 16,
        particlelife       = 5,
        particlelifespread = 16,
        particlesize       = 25,
        particlesizespread = 0,
        particlespeed      = 10,
        particlespeedspread = 3,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.5,
        sizemod            = 1,
        texture            = [[randdots]],
      },
    },
	
    fireballs = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      useairlos          = true,
      water              = true,
      alwaysVisible      = 0,
	  properties = {
        alwaysVisible      = 0,
	    airdrag            = 0.9,
        colormap           = [[1.0 1.0 1.0 0.04   0.9 0.5 0.2 0.01  0.8 0.1 0.1 0.01]],
        directional        = 1,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 15,
        particlelifespread = 5,
        particlesize       = 20,
        particlesizespread = 0,
        particlespeed      = 5,
        particlespeedspread = 5,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[tpsmoke2]],
      },
    },
	
    smokeballs = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      useairlos          = true,
      water              = true,
      alwaysVisible      = 0,
	  properties = {
        alwaysVisible      = 0,
	    airdrag            = 1,
        colormap           = [[0 0 0 0.5     0 0 0 0.2     0.1 0.1 0.1 0.1]],
        directional        = 1,
        emitrot            = 30,
        emitrotspread      = 10,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 18,
        particlelifespread = 5,
        particlesize       = 10,
        particlesizespread = 0,
        particlespeed      = 2,
        particlespeedspread = 2,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1.2,
        sizemod            = 1,
        texture            = [[tpsmoke2]],
      },
    },
	
    dirt = {
      air                = true,
	  count              = 4,
	  ground             = true,
	  underwater         = 1,
	  useairlos          = true,
	  water              = true,
	  alwaysVisible      = false,
	  properties = {
        alwaysVisible      = false,
		color              = [[0.2, 0.1, 0.05]],
		alphaFalloff       = 2,
		size               = 20,
		pos                = [[r-10 r10, 0, r-10 r10]],
		speed              = [[r1.5 r-1.5, 2, r1.5 r-1.5]],
	  },
	},
	
    ["groundflash"] = {
    
	  alwaysVisible        = 1,
      flashSize            = 150,
      flashAlpha           = 1,
      circleGrowth         = 5,
      circleAlpha          = 0.3,
      ttl                  = 13,
      color                = [[1 0.5 0]],
	  air                  = 1,
      ground               = 1,
      water                = 1,
   },
  
  },

}