--ct_explosion_unit_cruiser
--Explosion CEG for Cruisers
--by Sanada

return {
  ["ct_explosion_unit_cruiser"] = {  
	
    explosionspikes = {
      air                = true,
      class              = [[CExploSpikeProjectile]],
      count              = 8,
      ground             = true,
      underwater         = 1,
      useairlos          = false,
      water              = true,
      alwaysVisible      = false,
	  properties = {
        alwaysVisible      = false,
		dir                = [[-45 r90,-45 r90,-45 r90]],
		width              = 8,
		length             = 0.5,
		alpha              = 1,
		alphaDecay         = 0.12,
		color              = [[0.4, 0.4, 1]],
      },
    },
	
    explosionsphere = {
      air                = true,
      class              = [[CSpherePartSpawner]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      useairlos          = false,
      water              = true,
      alwaysVisible      = false,
	  properties = {
        alwaysVisible      = false,
		ttl                = 20,
		alpha              = 0.5,
		expansionSpeed     = [[10 r3]],
		color              = [[0.3, 0.3, 1]],
      },
    },
	
    explosionpoof = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 2,
      ground             = true,
      underwater         = 1,
      useairlos          = false,
      water              = true,
      alwaysVisible      = false,
	  properties = {
        alwaysVisible      = false,
	    airdrag            = 0.8,
        colormap           = [[1.0 1.0 1.0 0.04   0.5 0.2 0.9 0.01  0.1 0.1 0.8 0.01]],
        directional        = 1,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 20,
        particlelife       = 20,
        particlelifespread = 4,
        particlesize       = 20,
        particlesizespread = 10,
        particlespeed      = 6,
        particlespeedspread = 5,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1.01,
        texture            = [[tpsmoke2]],
      },
    },
	
    dirt = {
      air                = false,
	  count              = 4,
	  ground             = true,
	  underwater         = 1,
	  useairlos          = true,
	  water              = false,
	  alwaysVisible      = false,
	  properties = {
        alwaysVisible      = false,
		color              = [[0.1, 0.1, 0.05]],
		alphaFalloff       = 2,
		size               = 40,
		pos                = [[r-10 r10, 0, r-10 r10]],
		speed              = [[r1.5 r-1.5, 2, r1.5 r-1.5]],
	  },
	},
	
    smallpoofs = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      underwater         = 1,
      useairlos          = true,
      water              = true,
      alwaysVisible      = false,
	  properties = {
        alwaysVisible      = false,
	    airdrag            = 0.2,
        colormap           = [[1.0 1.0 1.0 0.04   0.0 0.0 0.5 0.01  0.1 0.1 0.1 0.01]],
        directional        = 0,
        emitrot            = 45,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.005, 0]],
        numparticles       = 30,
        particlelife       = 10,
        particlelifespread = 16,
        particlesize       = 15,
        particlesizespread = 0,
        particlespeed      = 19,
        particlespeedspread = 10,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0.8,
        sizemod            = 1,
        texture            = [[randdots]],
      },
    },
	
    ["groundflash"] = {
    
	  alwaysVisible        = 1,
      flashSize            = 150,
      flashAlpha           = 0.9,
      circleGrowth         = 10,
      circleAlpha          = 0.7,
      ttl                  = 18,
      color                = [[0.3 0.3 1]],
	  air                  = 1,
      ground               = 1,
      water                = 1,
   },
  
  },


}