--ct_impact_artillery
--Impact CEG for artillery
--by Sanada

return {
  ["ct_impact_artillery"] = {
    dirtpoofs = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 4,
      ground             = false,
      underwater         = 1,
	  unit               = false,
	  nounit             = true,
      useairlos          = true,
      water              = true,
      alwaysVisible      = 0,
	  properties = {
        alwaysVisible      = 0,
	    airdrag            = 0.9,
        colormap           = [[0.4 0.3 0.2 0.8    0.2 0.15 0.1 0.8    0.2 0.15 0.1 0.7     0.2 0.15 0.1 0.7]],
        directional        = 1,
        emitrot            = 5,
        emitrotspread      = 25,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -1, 0]],
        numparticles       = 20,
        particlelife       = 15,
        particlelifespread = 5,
        particlesize       = 5,
        particlesizespread = 0,
        particlespeed      = 15,
        particlespeedspread = 8,
        pos                = [[0, 2, 0]],
        sizegrowth         = 0,
        sizemod            = 1,
        texture            = [[tpsmoke2]],
      },
    },
	
    fireballs = {
      air                = false,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = false,
	  unit               = true,
	  nounit             = false,
      underwater         = 1,
      useairlos          = true,
      water              = true,
      alwaysVisible      = 0,
	  properties = {
        alwaysVisible      = 0,
	    airdrag            = 0.8,
        colormap           = [[1.0 1.0 1.0 0.04   0.9 0.5 0.2 0.01  0.8 0.1 0.1 0.01]],
        directional        = 1,
        emitrot            = 30,
        emitrotspread      = 32,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, -0.05, 0]],
        numparticles       = 8,
        particlelife       = 8,
        particlelifespread = 5,
        particlesize       = 8,
        particlesizespread = 0,
        particlespeed      = 5,
        particlespeedspread = 5,
        pos                = [[0, 2, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[tpsmoke2]],
      },
    },	
	
    heatcloud = {
	  air                  = true,
	  class                = [[CHeatCloudProjectile]],
	  count                = 1,
	  ground               = true,
	  underwater           = 1,
	  useairlos            = true,
	  water                = true,
	  alwaysVisible        = 0,
	  properties = {
	    heat                = 10,
		maxheat             = 15,
		heatFalloff         = 1.3,
		size                = 3,
		sizeGrowth          = 15,
		pos                 = [[0, 1, 0]],
		speed               = [[0, 1, 0]],
		texture             = [[flare]],
	  },
    },	

    ["groundflash"] = {
    
	alwaysVisible=0,
      flashSize = 16,
      flashAlpha = 0.95,
      circleGrowth = 0.8,
      circleAlpha = 0.3,
      ttl = 6,
      color = [[0.9 0.4 0.1]],
      alwaysvisible=0,
	  air=1,
      ground=1,
      water=1,
   },
  
  },


}